// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHi6RZurwhP6t4pMtDvjoEVViwis6_vr4',
    appId: '1:176716885111:web:20870e3b466aebe7e22a72',
    messagingSenderId: '176716885111',
    projectId: 'uas-made-sem4',
    authDomain: 'uas-made-sem4.firebaseapp.com',
    storageBucket: 'uas-made-sem4.appspot.com',
    measurementId: 'G-PJWSW8K6N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPxJBygJBbcsf1Bsu_fj4e6vWnFnx5Yo',
    appId: '1:176716885111:android:83b46e5edb980229e22a72',
    messagingSenderId: '176716885111',
    projectId: 'uas-made-sem4',
    storageBucket: 'uas-made-sem4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjJ1xjKQ2ovmVgTE4-f9xF2CTZzqvwA6E',
    appId: '1:176716885111:ios:b21579bf72a3a47ae22a72',
    messagingSenderId: '176716885111',
    projectId: 'uas-made-sem4',
    storageBucket: 'uas-made-sem4.appspot.com',
    iosClientId: '176716885111-vjrml315tdk52368o4tafg1busommn3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMadeSem4Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjJ1xjKQ2ovmVgTE4-f9xF2CTZzqvwA6E',
    appId: '1:176716885111:ios:5bb65f8b1b78cce1e22a72',
    messagingSenderId: '176716885111',
    projectId: 'uas-made-sem4',
    storageBucket: 'uas-made-sem4.appspot.com',
    iosClientId: '176716885111-iold5gq59mn733771in54m5nj1p55jfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMadeSem4Firebase.RunnerTests',
  );
}
